version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependencies"
    groups:
      aksel:
        patterns:
          - "@navikt/aksel*"
          - "@navikt/ds*"