export enum RolleType {
    BM = "BM",
    BP = "BP",
    BA = "BA",
    RM = "RM",
    FR = "FR",

    BIDRAGSPLIKTIG = "BIDRAGSPLIKTIG",
    BIDRAGSMOTTAKER = "BIDRAGSMOTTAKER",
    REELMOTTAKER = "REELMOTTAKER",
    BARN = "BARN",
    FEILREGISTRERT = "FEILREGISTRERT",

    // Deprecated
    BIDRAGS_PLIKTIG = "BIDRAGS_PLIKTIG",
    BIDRAGS_MOTTAKER = "BIDRAGS_MOTTAKER",
    REELL_MOTTAKER = "REELL_MOTTAKER",
}
