name: Build package
on:
  push:
    branches-ignore:
      - 'main'
env:
  NPM_TOKEN: ${{ secrets.READER_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build